# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
    ]
